apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: 
spec:
  hosts:
  - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        subset: v1
    retries:
      attempts: 4
      perTryTimeout: 3s